# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

mr:
  instance-type: prim
  task-reset-timeout-multiplier: 4.0
  task-warning-timeout-multiplier: 2.0
  task-successful-runs-timeout-multiplier: 8.0
  cache:
    user-email-list:
      invalidation-interval: PT10M
      max-size: 500
    traversal-purchase:
      invalidation-interval: PT2M
      max-size: 500
    traversal-pi:
      invalidation-interval: PT5M
      max-size: 500
    traversal-user:
      invalidation-interval: PT1M
      max-size: 200
  tasks:
    resolution-sending-task:
      enabled: true
      delay: PT2M
    prim-health-analysis-task:
      enabled: true
      delay: PT1M
    sec-health-analysis-task:
      enabled: false
      delay: PT1M
    residual-queue-reconciliation-task:
      enabled: true
      delay: PT10M
    queue-size-calculation-task:
      enabled: true
      delay: PT10M
    overall-size-calculation-task:
      enabled: true
      delay: PT10M
    item-assignment-reconciliation-task:
      enabled: true
      delay: PT1M
      timeout: PT5M
      comprehensive-check:
        period: PT30M
      partial-check:
        observed-period: PT5M
    item-unlock-task:
      enabled: true
      delay: PT1M
    item-enrichment-task:
      enabled: true
      delay: PT1M
      timeout: PT5M
      enrichment-delay: PT5M
      max-enrichment-delay: PT15M
      max-enrichment-attempts: 10
      history-depth: 20
    dictionary-reconciliation-task:
      enabled: true
      delay: PT1H
    queue-assignment-reconciliation-task:
      enabled: true
      delay: PT10M
  items:
    unlock-timeout: PT30M
    near-to-timeout: PT15M
    near-to-sla: P2D
  dictionary:
    ttl: P14D
  search-query:
    ttl: P30D
  link-analysis:
    ttl: P1D
#    check-user-restriction: true
    check-user-restriction: false
  email-domain:
    ttl: P7D


azure:
  cosmosdb:
    default-ttl: P183D
  graph-api:
    role-assignments-url: https://graph.microsoft.com/v1.0/servicePrincipals/${DFP_SP_ID}/appRoleAssignedTo
    user-role-assignments-url-template: https://graph.microsoft.com/v1.0/users/#user_id#/appRoleAssignments?$filter=resourceId eq ${DFP_SP_ID}
    users-url: https://graph.microsoft.com/v1.0/users
    user-url-template: https://graph.microsoft.com/v1.0/users/#user_id#
    app-service-principal-url: https://graph.microsoft.com/v1.0/servicePrincipals/${DFP_SP_ID}
    user-photo-url-template: https://graph.microsoft.com/beta/users/#user_id#/photo/$value
    timeout: PT5S
    retries: 2
    role-mapping:
      ManualReviewFraudManager: ADMIN_MANAGER
      ManualReviewSeniorAnalyst: SENIOR_ANALYST
      ManualReviewAnalyst: ANALYST
  dfp:
    link-analysis-full-url: https://${CLIENT_TENANT_SHORT_NAME}-${CLIENT_TENANT_ID}.api.dfp.dynamics.com/knowledgegateway/v1.0/customersupport/connectedentities?queryType=full
    link-analysis-count-url: https://${CLIENT_TENANT_SHORT_NAME}-${CLIENT_TENANT_ID}.api.dfp.dynamics.com/knowledgegateway/v1.0/customersupport/connectedentities?queryType=count
    link-analysis-details-url: https://${CLIENT_TENANT_SHORT_NAME}-${CLIENT_TENANT_ID}.api.dfp.dynamics.com/knowledgegateway/v1.0/customersupport/purchasedetails
    graph-explorer-url: https://${CLIENT_TENANT_SHORT_NAME}-${CLIENT_TENANT_ID}.api.dfp.dynamics.com/knowledgegateway/customersupport/v1.0/explorer/traversal
    user-email-list-url: https://${CLIENT_TENANT_SHORT_NAME}-${CLIENT_TENANT_ID}.api.dfp.dynamics.com/knowledgegateway/v1.0/sparta/customersupport/lists/status/User.Email
    purchase-event-url: https://${CLIENT_TENANT_SHORT_NAME}-${CLIENT_TENANT_ID}.api.dfp.dynamics.com/v1.0/merchantservices/events/Purchase
    bank-event-url: https://${CLIENT_TENANT_SHORT_NAME}-${CLIENT_TENANT_ID}.api.dfp.dynamics.com/v1.0/merchantservices/events/BankEvent
  dfp-auth:
    token-cache-size: 500
    token-cache-retention: PT10M
  event-hub:
    sending-timeout: PT20S
    health-check-ttl: PT24H
    health-check-batch-size: 2
    health-check-allowed-delay: PT60M
    consumers:
      dfp-hub:
        checkpoint-interval: PT1M
    producers:
      item-lock-event-hub:
        sending-period: PT1S
        sending-workers: 4
        buffer-size: 100
      item-label-event-hub:
        sending-period: PT1S
        sending-workers: 4
        buffer-size: 10
      item-resolution-event-hub:
        sending-period: PT1S
        sending-workers: 6
        buffer-size: 10
      item-assignment-event-hub:
        sending-period: PT2S
        sending-workers: 6
        buffer-size: 1000
      queue-size-event-hub:
        sending-period: PT1S
        sending-workers: 4
        buffer-size: 200
      queue-update-event-hub:
        sending-period: PT1S
        sending-workers: 4
        buffer-size: 100
      overall-size-event-hub:
        sending-period: PT1S
        sending-workers: 4
        buffer-size: 100

swagger:
  auth-url: https://login.microsoftonline.com/${CLIENT_TENANT_ID}/oauth2/authorize?resource=${CLIENT_ID}

spring:
  security:
    oauth2:
      client:
        registration:
          azure-maps-api:
            scope: https://atlas.microsoft.com/.default
          azure-graph-api:
            scope: https://graph.microsoft.com/.default
          azure-dfp-api:
            scope: https://api.dfp.microsoft.com/.default
          azure-dfp-la-api:
            scope: https://api.dfp.microsoft.com/.default
        provider:
          azure-maps-api:
            token-uri: https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token
          azure-graph-api:
            token-uri: https://login.microsoftonline.com/${CLIENT_TENANT_ID}/oauth2/v2.0/token
          azure-dfp-api:
            token-uri: https://login.microsoftonline.com/${CLIENT_TENANT_ID}/oauth2/v2.0/token
          azure-dfp-la-api:
            token-uri: https://login.microsoftonline.com/${CLIENT_TENANT_ID}/oauth2/v2.0/token

resilience4j.retry:
  instances:
    cosmosOptimisticCapture:
      maxRetryAttempts: 30
      waitDuration: 10ms
    cosmosOptimisticUpdate:
      maxRetryAttempts: 3
      waitDuration: 100ms
